# Generated by Django 5.1.7 on 2026-01-23 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_gender_alter_profile_user_application_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy_record',
            name='vacancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_record', to='api.vacancy'),
        ),
    ]
